services:
  - type: web
    name: intellidoc-ai-service
    env: python
    region: oregon
    plan: free
    rootDir: ai_service
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: ALLOWED_ORIGIN
        sync: false
      - key: AWS_REGION
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: S3_BUCKET
        sync: false
      - key: S3_BUCKET_NAME
        sync: false
      - key: S3_ENDPOINT
        sync: false
      - key: S3_FORCE_PATH_STYLE
        sync: false
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: RABBITMQ_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
